function Rex=Rex_Hyper_onepool(da,w1,di,ki,ka,r2i)
% calculate Rex HyperCEST solution for pool i
%JCP paper;   assumes (R1B<<kBA, Reff<<R2B)
Rex =   -((ka.*ki.*w1.^2.*((-da+di).^2 + (r2i.*(da.^2 + (ka + ki).^2 + ki.*r2i + w1.^2))./ki))./...
        ((ka + ki).*(di.^2.*w1.^2 + ka.*r2i.*w1.^2) + ...
        (ka + ki).*((da.*di - ka.*r2i).^2 + (di.*ka + da.*(ki + r2i)).^2 + ...
        (ka + ki + r2i).^2.*w1.^2) + (ka + ki + r2i).*(da.^2.*w1.^2 + w1.^4)));
end